final Map<String, dynamic> mockStudentCertificationsData = {
  "status": 200,
  "data": {
    "completed_certifications": [
      {
        "id": "1",
        "title": "Introduction to Criminal Law",
        "description": "Learn the foundational principles of criminal offenses and defenses",
        "startDate": "2024-01-15",
        "endDate": "2024-03-15",
        "certificateImage": "",
        "isCompleted": true,
        "duration": "2 months",
        "instructor": "Adv. Raza Khan",
        "level": "Beginner",
        "skills": ["Criminal Procedure", "Evidence", "Case Law"],
      },
      {
        "id": "2",
        "title": "Advanced Corporate Law",
        "description": "Master corporate regulations, mergers, and business legalities",
        "startDate": "2024-02-01",
        "endDate": "2024-04-01",
        "certificateImage": "",
        "isCompleted": true,
        "duration": "2 months",
        "instructor": "Adv. Fatima Ahmed",
        "level": "Intermediate",
        "skills": ["Mergers", "Contracts", "Corporate Governance"],
      },
    ],
    "available_certifications": [
      {
        "id": "3",
        "title": "International Human Rights Law",
        "description": "Explore global treaties, human rights issues, and international courts",
        "startDate": "2024-03-01",
        "endDate": "2024-05-01",
        "certificateImage": "",
        "isCompleted": false,
        "duration": "2 months",
        "instructor": "Dr. Michael Chen",
        "level": "Intermediate",
        "skills": ["Human Rights", "Treaties", "Global Law"],
      },
      {
        "id": "4",
        "title": "Cybercrime & Digital Evidence",
        "description": "Understand the legal frameworks surrounding digital crimes and evidence",
        "startDate": "2024-03-15",
        "endDate": "2024-05-15",
        "certificateImage": "",
        "isCompleted": false,
        "duration": "2 months",
        "instructor": "Emily Davis",
        "level": "Beginner",
        "skills": ["Digital Evidence", "Cyber Security", "Data Privacy"],
      },
      {
        "id": "5",
        "title": "Family Law & Custody Rights",
        "description": "Master the complexities of marriage, divorce, and child custody",
        "startDate": "2024-04-01",
        "endDate": "2024-06-01",
        "certificateImage": "",
        "isCompleted": false,
        "duration": "2 months",
        "instructor": "Robert Wilson",
        "level": "Advanced",
        "skills": ["Family Law", "Custody", "Divorce Proceedings"],
      },
      {
        "id": "6",
        "title": "Intellectual Property Law",
        "description": "Introduction to patents, trademarks, and copyright laws",
        "startDate": "2024-04-15",
        "endDate": "2024-06-15",
        "certificateImage": "",
        "isCompleted": false,
        "duration": "2 months",
        "instructor": "Dr. Lisa Anderson",
        "level": "Advanced",
        "skills": ["Patents", "Trademarks", "Copyrights", "IP Litigation"],
      },
    ],
  },
};
